files:
  - 
    source: contributors.txt
    translation: /%language%/%original_file_name%
  - 
    source: README.md
    translation: '%original_file_name%'
  - 
    source: /*.csv
    translation: '%original_file_name%'
